In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a2)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
print(a2.shape)
print(a2.shape[0])
print(a2.shape[1])

(2, 5)
2
5


In [9]:
print(a2[0,:])
print(a2[1,2:5])
print(a2[1,:])

[1 2 3 4 5]
[ 8  9 10]
[ 6  7  8  9 10]


In [10]:
b=a2[a2>6]
print(b)

[ 7  8  9 10]


In [11]:
print(a2>6)

[[False False False False False]
 [False  True  True  True  True]]


In [12]:
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
a2[a2>6]=0
print(a2)

[[1 2 3 4 5]
 [6 0 0 0 0]]


In [19]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print(np.hstack([a1,a2]))

[[1 2 5 6]
 [3 4 7 8]]


In [15]:
print(np.vstack((a1,a2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
a1=np.arange(5,10)
print(a1)

[5 6 7 8 9]


In [22]:
a2=np.arange(5,20,2)
print(a2)

[ 5  7  9 11 13 15 17 19]


In [11]:
a=np.linspace(0,10,)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [10]:
a=np.logspace(0,2,5)
print(a)

[  1.           3.16227766  10.          31.6227766  100.        ]


In [30]:
a_ones=np.ones((3,4))
print(a_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
a_zeros=np.zeros((3,4))
print(a_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
a_eyes=np.eye(3)
print(a_eyes)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
a_empty=np.empty((3,4))
print(a_empty)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
a="abcdef"
b=np.fromstring(a,dtype=np.int8)
print(b)

[ 97  98  99 100 101 102]


/Users/devz/PycharmProjects/py3_venv/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


In [38]:
def func(i,j):
    return i+j

a=np.fromfunction(func,(5,6))
print(a)

[[0. 1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6. 7.]
 [3. 4. 5. 6. 7. 8.]
 [4. 5. 6. 7. 8. 9.]]


In [39]:
a1=np.array([[4,5,6],[1,2,3]])
a2=np.array([[6,5,4],[3,2,1]])
print(a1+a2)

[[10 10 10]
 [ 4  4  4]]


In [40]:
print(a1/a2)

[[0.66666667 1.         1.5       ]
 [0.33333333 1.         3.        ]]


In [41]:
print(a1%a2)

[[4 0 2]
 [1 0 0]]


In [42]:
a=np.array([[1,2,3],[4,5,6]])
print(np.sin(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [43]:
print(np.arcsin(a))

[[1.57079633        nan        nan]
 [       nan        nan        nan]]


/Users/devz/PycharmProjects/py3_venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


In [44]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[1,2],[3,4],[5,6]])
print(a1.shape[1],a2.shape[0])

3 3


In [47]:
print(a1.dot(a2))

[[22 28]
 [49 64]]


In [51]:
a=a1
print(a)
print(a.transpose())
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [55]:
a=np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
import numpy.linalg as lg
print(lg.inv(a))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [56]:
a=np.eye(3)
print(lg.inv(a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [63]:
a=np.array([[1,2,3],[4,5,7]])
print(a.max())
print(a.min())
print(a.max(axis=0))
print(a.max(axis=1))
print(a.argmax(axis=1))

7
1
[4 5 7]
[3 7]
[2 2]


In [65]:
print(a.mean())

3.6666666666666665


In [69]:
print(a)
print(a.mean(axis=0))

[[1 2 3]
 [4 5 7]]
[2.5 3.5 5. ]


In [67]:
print(a.mean(axis=1))

[2.         5.33333333]


In [68]:
#axis =0 按列执行
#axis =1 按行执行


In [70]:
print(a.var())

3.8888888888888893


In [71]:
print(a.var(axis=0))

[2.25 2.25 4.  ]


In [72]:
print(a.var(axis=1))

[0.66666667 1.55555556]


In [73]:
print(a.std())
print(a.std(axis=0))
print(a.std(axis=1))

1.9720265943665387
[1.5 1.5 2. ]
[0.81649658 1.24721913]


In [75]:
print(np.median(a))

3.5
